### ISSUE TITLE
Found waker not created by the Embassy executor. `embassy_time::Timer` only works with the Embassy executor.

### ISSUE THREAD

**Issue by PhaestusFox** [embassy-rs/embassy#2100]
I don't know what I did but my Pico not just crashes with this error any time I try to use a Timer or Ticker, this was working fine this afternoon but stopped after a cargo update.

I have made a minimal example to recreate it:
cargo.toml
```
[package]
name = "time_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-executor = { version = "0.3.0", git = "https://github.com/embassy-rs/embassy", features = ["nightly", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"]  }
embassy-time = { version = "0.1.5", git = "https://github.com/embassy-rs/embassy", features = ["nightly", "unstable-traits", "defmt", "defmt-timestamp-uptime"]  }
embassy-rp = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy", features = ["defmt", "unstable-traits", "nightly", "unstable-pac", "time-driver", "critical-section-impl"]  }
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
cortex-m-rt = "0.7.0"
cortex-m = { version = "0.7.6", features = ["inline-asm"] }
```

main.rs
```
#![no_std]
#![no_main]
#![feature(type_alias_impl_trait)]
use embassy_executor::Spawner;
use embassy_time::{Timer, Duration};
use {defmt_rtt as _, panic_probe as _};
use embassy_rp::{bind_interrupts, pio::InterruptHandler, peripherals::PIO0};

bind_interrupts!(struct Irqs {
    PIO0_IRQ_0 => InterruptHandler<PIO0>;
});

#[embassy_executor::main]
async fn main(_spawner: Spawner) {
    Timer::after(Duration::from_millis(10)).await
}
```

also have memory.x and build.rs from the pi examples

here is the full error message when I run this using a Pico probe:
```
0.000538 ERROR panicked at 'Found waker not created by the Embassy executor. `embassy_time::Timer` only works with the Embassy executor.'
└─ embassy_executor::raw::waker::task_from_waker @ C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-executor\src\fmt.rs:106 
0.000596 ERROR panicked at C:\Users\Phox\.cargo\registry\src\index.crates.io-6f17d22bba15001f\defmt-0.3.5\src\lib.rs:368:5:
explicit panic
└─ panic_probe::print_defmt::print @ C:\Users\Phox\.cargo\registry\src\index.crates.io-6f17d22bba15001f\panic-probe-0.3.1\src\lib.rs:104
DEBUG probe_rs::debug::unit_info: Found DIE, now checking for inlined functions: name=None
DEBUG probe_rs::debug::unit_info: Found DIE, now checking for inlined functions: name=None
DEBUG probe_rs::debug::debug_info: UNWIND: Callsite for inlined function None
DEBUG probe_rs::debug::debug_info: UNWIND: Callsite for inlined function None
DEBUG probe_rs::debug::debug_info: UNWIND: Callsite for inlined function None
DEBUG probe_rs::debug::debug_info: UNWIND: Callsite for inlined function None
DEBUG probe_rs::debug::unit_info: Found DIE, now checking for inlined functions: name=None
Frame 0: HardFault @ 0x1000283c
Frame 1: __udf @ 0x10000ca2 inline
       C:\Users\Phox\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cortex-m-0.7.7\src\..\asm/inline.rs:181:5
Frame 2: udf @ 0x0000000010000ca2 inline
       C:\Users\Phox\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cortex-m-0.7.7\src/call_asm.rs:11:43
Frame 3: hard_fault @ 0x0000000010000ca2 inline
       C:\Users\Phox\.cargo\registry\src\index.crates.io-6f17d22bba15001f\panic-probe-0.3.1\src/lib.rs:86:5
Frame 4: panic @ 0x0000000010000ca2
       C:\Users\Phox\.cargo\registry\src\index.crates.io-6f17d22bba15001f\panic-probe-0.3.1\src/lib.rs:54:9
Frame 5: panic_fmt @ 0x10001832
       /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07\library/core/src/panicking.rs:72:14
Frame 6: panic_display<&str> @ 0x10001890 inline
       /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07\library/core/src/panicking.rs:178:5
Frame 7: panic_explicit @ 0x0000000010001872
       /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07\library/core/src/panicking.rs:160:5
Frame 8: panic_cold_explicit @ 0x10001632
       C:/rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/core/src/panic.rs:87:13
Frame 9: default_panic @ 0x10001624
       C:\Users\Phox\.cargo\registry\src\index.crates.io-6f17d22bba15001f\defmt-0.3.5\src/lib.rs:368:5
Frame 10: panic @ 0x100013ca inline
       C:\Users\Phox\.cargo\registry\src\index.crates.io-6f17d22bba15001f\defmt-0.3.5\src\export/mod.rs:133:14
Frame 11: task_from_waker @ 0x00000000100013c6 inline
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-executor\src/fmt.rs:106:13
Frame 12: schedule_wake @ 0x00000000100013b4 inline
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-executor\src\raw/mod.rs:600:20
Frame 13: _embassy_time_schedule_wake @ 0x00000000100013b4
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-time\src/queue.rs:55:13
Frame 14: schedule_wake @ 0x10001492 inline
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-time\src/timer.rs
Frame 15: poll @ 0x000000001000148c
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-time\src/timer.rs:113:13
Frame 16: {async_fn#0} @ 0x10000244 inline
       G:\RustStuff\Projects\dry_box\time_test\src/main.rs
Frame 17: <unknown function @ 0x10000244> @ 0x0000000010000240
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-executor\src\raw/mod.rs:161:15
Frame 18: <unknown function @ 0x10001252> @ 0x10001252 inline
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-executor\src\raw/util.rs:55:9
Frame 19: <unknown function @ 0x10001252> @ 0x0000000010001252 inline
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-executor\src\raw/timer_queue.rs:34:28
Frame 20: {closure#0} @ 0x0000000010001252 inline
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-executor\src\raw/mod.rs:418:17
Frame 21: <unknown function @ 0x10001252> @ 0x0000000010001238 inline
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-executor\src\raw/run_queue.rs:85:13
Frame 22: <unknown function @ 0x10001252> @ 0x000000001000121a inline
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-executor\src\raw/mod.rs:391:13
Frame 23: <unknown function @ 0x10001252> @ 0x0000000010001178
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-executor\src\raw/mod.rs:532:9
Frame 24: <unknown function @ 0x100002dc> @ 0x100002dc
       C:\Users\Phox\.cargo\git\checkouts\embassy-9312dcb0ed774b29\e70c531\embassy-executor\src\arch/cortex_m.rs:107:21
Frame 25: __cortex_m_rt_main @ 0x1000041a
       G:\RustStuff\Projects\dry_box\time_test\src/main.rs:13:1
Frame 26: __cortex_m_rt_main_trampoline @ 0x10000404
       G:\RustStuff\Projects\dry_box\time_test\src/main.rs:13:1
Frame 27: <unknown function @ 0x100001e6> @ 0x100001e6
Frame 28: <unknown function @ 0x100001e6> @ 0x100001e6
Error: CPU halted unexpectedly.
error: process didn't exit successfully: `probe-rs run --chip RP2040 G:\RustStuff\Projects\dry_box\target\thumbv6m-none-eabi\release\time_test` (exit code: 1)
```

**Comment by Verequies** [comment]
I have also encountered this issue. It is fixed if you downgrade to a prior version of Rust nightly. Seems like something changed in the last few days has caused Embassy to crash on start on the RP2040.

**Comment by DCNick3** [comment]
This was reported to rustc as https://github.com/rust-lang/rust/issues/117047

**Comment by AzazKamaz** [comment]
Several alternative ways to fix, in file `embassy-executor/src/raw/waker.rs`:
- make `VTABLE` `static` instead of `const` - probably proper way to fix
- make `VTABLE` functions `inline(never)` - `clone()`, `wake()`, `drop()`
- make functions that refer `VTABLE` `inline(never)` - `clone()`, `from_task()`, `task_from_waker()`

Also you can just disable cross-crate inlining with `-Zcross-crate-inline-threshold=0` compiler option

**Comment by Dirbaio** [comment]
fixed in #2112

**Comment by Leandros** [comment]
Still appears to be happening with `embassy-executor` v0.7 and v0.8, using the following set of dependencies:

```toml
embassy-time = { version = "0.5", features = ["defmt-timestamp-uptime", "defmt"] }
embassy-stm32 = { version = "0.3.0", features = ["defmt", "memory-x", "stm32f207zg", "exti", "time-driver-any", "rt", "unstable-pac", "time"] }
embassy-usb = { version = "0.5", features = ["defmt"] }
embassy-sync = { version = "0.7", features = ["defmt"] }
embassy-futures = { version = "0.1", features = ["defmt"] }
embassy-executor = { version = "0.7", features = ["arch-cortex-m", "defmt", "executor-thread"] }

cortex-m = { version = "0.7", features = ["critical-section-single-core", "inline-asm"] }
cortex-m-rt = "0.7"
```

Running on an STMicro NUCLEO-F207ZG.


```
ERROR panicked at /Users/arvidgerstmann/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-executor-0.8.0/src/raw/waker.rs:38:9:
Found waker not created by the Embassy executor. `embassy_time::Timer` only works with the Embassy executor.
└─ panic_probe::print_defmt::print @ /Users/arvidgerstmann/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/panic-probe-1.0.0/src/lib.rs:104
```

with toolchain:

```
rustc 1.90.0 (1159e78c4 2025-09-14)
binary: rustc
commit-hash: 1159e78c4747b02ef996e55082b704c09b970588
commit-date: 2025-09-14
host: aarch64-apple-darwin
release: 1.90.0
LLVM version: 20.1.8
```

and it's still fixed by enabling: `-Zcross-crate-inline-threshold=0`.

<details>
<summary>`cargo tree` output</summary>

```
datalogger v0.0.0 (/Users/arvidgerstmann/workspace/_private/__embedded/ReflowController/aux/datalogger)
├── cortex-m v0.7.7
│   ├── bare-metal v0.2.5
│   │   [build-dependencies]
│   │   └── rustc_version v0.2.3
│   │       └── semver v0.9.0
│   │           └── semver-parser v0.7.0
│   ├── bitfield v0.13.2
│   ├── critical-section v1.2.0
│   ├── embedded-hal v0.2.7
│   │   ├── nb v0.1.3
│   │   │   └── nb v1.1.0
│   │   └── void v1.0.2
│   └── volatile-register v0.2.2
│       └── vcell v0.1.3
├── cortex-m-rt v0.7.5
│   └── cortex-m-rt-macros v0.7.5 (proc-macro)
│       ├── proc-macro2 v1.0.101
│       │   └── unicode-ident v1.0.20
│       ├── quote v1.0.41
│       │   └── proc-macro2 v1.0.101 (*)
│       └── syn v2.0.107
│           ├── proc-macro2 v1.0.101 (*)
│           ├── quote v1.0.41 (*)
│           └── unicode-ident v1.0.20
├── datalogger-icd v0.0.0 (/Users/arvidgerstmann/workspace/_private/__embedded/ReflowController/datalogger-icd)
│   ├── postcard v1.1.3
│   │   ├── cobs v0.3.0
│   │   │   └── thiserror v2.0.17
│   │   │       └── thiserror-impl v2.0.17 (proc-macro)
│   │   │           ├── proc-macro2 v1.0.101 (*)
│   │   │           ├── quote v1.0.41 (*)
│   │   │           └── syn v2.0.107 (*)
│   │   ├── defmt v1.0.1
│   │   │   ├── bitflags v1.3.2
│   │   │   └── defmt-macros v1.0.1 (proc-macro)
│   │   │       ├── defmt-parser v1.0.0
│   │   │       │   └── thiserror v2.0.17
│   │   │       │       └── thiserror-impl v2.0.17 (proc-macro) (*)
│   │   │       ├── proc-macro-error2 v2.0.1
│   │   │       │   ├── proc-macro-error-attr2 v2.0.0 (proc-macro)
│   │   │       │   │   ├── proc-macro2 v1.0.101 (*)
│   │   │       │   │   └── quote v1.0.41 (*)
│   │   │       │   ├── proc-macro2 v1.0.101 (*)
│   │   │       │   ├── quote v1.0.41 (*)
│   │   │       │   └── syn v2.0.107 (*)
│   │   │       ├── proc-macro2 v1.0.101 (*)
│   │   │       ├── quote v1.0.41 (*)
│   │   │       └── syn v2.0.107 (*)
│   │   ├── heapless v0.7.17
│   │   │   ├── hash32 v0.2.1
│   │   │   │   └── byteorder v1.5.0
│   │   │   ├── serde v1.0.228
│   │   │   │   ├── serde_core v1.0.228
│   │   │   │   └── serde_derive v1.0.228 (proc-macro)
│   │   │   │       ├── proc-macro2 v1.0.101 (*)
│   │   │   │       ├── quote v1.0.41 (*)
│   │   │   │       └── syn v2.0.107 (*)
│   │   │   └── stable_deref_trait v1.2.1
│   │   │   [build-dependencies]
│   │   │   └── rustc_version v0.4.1
│   │   │       └── semver v1.0.27
│   │   ├── postcard-derive v0.2.2 (proc-macro)
│   │   │   ├── proc-macro2 v1.0.101 (*)
│   │   │   ├── quote v1.0.41 (*)
│   │   │   └── syn v2.0.107 (*)
│   │   └── serde v1.0.228 (*)
│   ├── postcard-rpc v0.11.15
│   │   ├── embassy-executor v0.7.0
│   │   │   ├── cortex-m v0.7.7 (*)
│   │   │   ├── critical-section v1.2.0
│   │   │   ├── defmt v0.3.100
│   │   │   │   └── defmt v1.0.1 (*)
│   │   │   ├── document-features v0.2.11 (proc-macro)
│   │   │   │   └── litrs v0.4.2
│   │   │   └── embassy-executor-macros v0.6.2 (proc-macro)
│   │   │       ├── darling v0.20.11
│   │   │       │   ├── darling_core v0.20.11
│   │   │       │   │   ├── fnv v1.0.7
│   │   │       │   │   ├── ident_case v1.0.1
│   │   │       │   │   ├── proc-macro2 v1.0.101 (*)
│   │   │       │   │   ├── quote v1.0.41 (*)
│   │   │       │   │   ├── strsim v0.11.1
│   │   │       │   │   └── syn v2.0.107 (*)
│   │   │       │   └── darling_macro v0.20.11 (proc-macro)
│   │   │       │       ├── darling_core v0.20.11 (*)
│   │   │       │       ├── quote v1.0.41 (*)
│   │   │       │       └── syn v2.0.107 (*)
│   │   │       ├── proc-macro2 v1.0.101 (*)
│   │   │       ├── quote v1.0.41 (*)
│   │   │       └── syn v2.0.107 (*)
│   │   ├── embassy-futures v0.1.2
│   │   │   └── defmt v1.0.1 (*)
│   │   ├── embassy-sync v0.7.2
│   │   │   ├── cfg-if v1.0.4
│   │   │   ├── critical-section v1.2.0
│   │   │   ├── defmt v1.0.1 (*)
│   │   │   ├── embedded-io-async v0.6.1
│   │   │   │   ├── defmt v0.3.100 (*)
│   │   │   │   └── embedded-io v0.6.1
│   │   │   │       └── defmt v0.3.100 (*)
│   │   │   ├── futures-core v0.3.31
│   │   │   ├── futures-sink v0.3.31
│   │   │   └── heapless v0.8.0
│   │   │       ├── hash32 v0.3.1
│   │   │       │   └── byteorder v1.5.0
│   │   │       └── stable_deref_trait v1.2.1
│   │   ├── embassy-time v0.4.0
│   │   │   ├── cfg-if v1.0.4
│   │   │   ├── critical-section v1.2.0
│   │   │   ├── defmt v0.3.100 (*)
│   │   │   ├── document-features v0.2.11 (proc-macro) (*)
│   │   │   ├── embassy-time-driver v0.2.1
│   │   │   │   └── document-features v0.2.11 (proc-macro) (*)
│   │   │   ├── embedded-hal v0.2.7 (*)
│   │   │   ├── embedded-hal v1.0.0
│   │   │   ├── embedded-hal-async v1.0.0
│   │   │   │   └── embedded-hal v1.0.0
│   │   │   └── futures-util v0.3.31
│   │   │       ├── futures-core v0.3.31
│   │   │       ├── futures-task v0.3.31
│   │   │       ├── pin-project-lite v0.2.16
│   │   │       └── pin-utils v0.1.0
│   │   ├── embassy-usb v0.5.1
│   │   │   ├── defmt v1.0.1 (*)
│   │   │   ├── embassy-futures v0.1.2 (*)
│   │   │   ├── embassy-net-driver-channel v0.3.2
│   │   │   │   ├── embassy-futures v0.1.2 (*)
│   │   │   │   ├── embassy-net-driver v0.2.0
│   │   │   │   │   └── defmt v0.3.100 (*)
│   │   │   │   └── embassy-sync v0.7.2 (*)
│   │   │   ├── embassy-sync v0.7.2 (*)
│   │   │   ├── embassy-usb-driver v0.2.0
│   │   │   │   ├── defmt v1.0.1 (*)
│   │   │   │   └── embedded-io-async v0.6.1 (*)
│   │   │   ├── embedded-io-async v0.6.1 (*)
│   │   │   ├── heapless v0.8.0 (*)
│   │   │   ├── ssmarshal v1.0.0
│   │   │   │   ├── encode_unicode v0.3.6
│   │   │   │   └── serde v1.0.228 (*)
│   │   │   └── usbd-hid v0.8.2
│   │   │       ├── serde v1.0.228 (*)
│   │   │       ├── ssmarshal v1.0.0 (*)
│   │   │       ├── usb-device v0.3.2
│   │   │       │   ├── heapless v0.8.0 (*)
│   │   │       │   └── portable-atomic v1.11.1
│   │   │       └── usbd-hid-macros v0.8.2 (proc-macro)
│   │   │           ├── byteorder v1.5.0
│   │   │           ├── hashbrown v0.13.2
│   │   │           │   └── ahash v0.8.12
│   │   │           │       ├── cfg-if v1.0.4
│   │   │           │       ├── once_cell v1.21.3
│   │   │           │       └── zerocopy v0.8.27
│   │   │           │       [build-dependencies]
│   │   │           │       └── version_check v0.9.5
│   │   │           ├── log v0.4.28
│   │   │           ├── proc-macro2 v1.0.101 (*)
│   │   │           ├── quote v1.0.41 (*)
│   │   │           ├── serde v1.0.228
│   │   │           │   └── serde_core v1.0.228
│   │   │           ├── syn v1.0.109
│   │   │           │   ├── proc-macro2 v1.0.101 (*)
│   │   │           │   ├── quote v1.0.41 (*)
│   │   │           │   └── unicode-ident v1.0.20
│   │   │           └── usbd-hid-descriptors v0.8.2
│   │   │               └── bitfield v0.14.0
│   │   ├── embassy-usb-driver v0.2.0 (*)
│   │   ├── heapless v0.8.0 (*)
│   │   ├── portable-atomic v1.11.1
│   │   ├── postcard v1.1.3 (*)
│   │   ├── postcard-schema v0.2.5
│   │   │   ├── postcard-derive v0.2.2 (proc-macro) (*)
│   │   │   └── serde v1.0.228 (*)
│   │   ├── serde v1.0.228 (*)
│   │   ├── static_cell v2.1.1
│   │   │   └── portable-atomic v1.11.1
│   │   └── thiserror v2.0.17 (*)
│   ├── postcard-schema v0.2.5 (*)
│   └── serde v1.0.228 (*)
├── defmt v1.0.1 (*)
├── defmt-rtt v1.1.0
│   ├── critical-section v1.2.0
│   └── defmt v1.0.1 (*)
├── embassy-executor v0.7.0 (*)
├── embassy-futures v0.1.2 (*)
├── embassy-stm32 v0.3.0
│   ├── aligned v0.4.2
│   │   └── as-slice v0.2.1
│   │       └── stable_deref_trait v1.2.1
│   ├── bit_field v0.10.3
│   ├── bitflags v2.10.0
│   ├── block-device-driver v0.2.0
│   │   └── aligned v0.4.2 (*)
│   ├── cfg-if v1.0.4
│   ├── cortex-m v0.7.7 (*)
│   ├── cortex-m-rt v0.7.5 (*)
│   ├── critical-section v1.2.0
│   ├── defmt v1.0.1 (*)
│   ├── document-features v0.2.11 (proc-macro) (*)
│   ├── embassy-embedded-hal v0.4.0
│   │   ├── defmt v1.0.1 (*)
│   │   ├── embassy-futures v0.1.2 (*)
│   │   ├── embassy-hal-internal v0.3.0
│   │   │   ├── cortex-m v0.7.7 (*)
│   │   │   ├── critical-section v1.2.0
│   │   │   ├── defmt v1.0.1 (*)
│   │   │   └── num-traits v0.2.19
│   │   │       [build-dependencies]
│   │   │       └── autocfg v1.5.0
│   │   ├── embassy-sync v0.7.2 (*)
│   │   ├── embassy-time v0.4.0 (*)
│   │   ├── embedded-hal v0.2.7 (*)
│   │   ├── embedded-hal v1.0.0
│   │   ├── embedded-hal-async v1.0.0 (*)
│   │   ├── embedded-storage v0.3.1
│   │   ├── embedded-storage-async v0.4.1
│   │   │   └── embedded-storage v0.3.1
│   │   └── nb v1.1.0
│   ├── embassy-futures v0.1.2 (*)
│   ├── embassy-hal-internal v0.3.0 (*)
│   ├── embassy-net-driver v0.2.0 (*)
│   ├── embassy-sync v0.7.2 (*)
│   ├── embassy-time v0.4.0 (*)
│   ├── embassy-time-driver v0.2.1 (*)
│   ├── embassy-time-queue-utils v0.2.0
│   │   ├── embassy-executor v0.8.0
│   │   │   ├── critical-section v1.2.0
│   │   │   ├── document-features v0.2.11 (proc-macro) (*)
│   │   │   └── embassy-executor-macros v0.7.0 (proc-macro)
│   │   │       ├── darling v0.20.11 (*)
│   │   │       ├── proc-macro2 v1.0.101 (*)
│   │   │       ├── quote v1.0.41 (*)
│   │   │       └── syn v2.0.107 (*)
│   │   └── heapless v0.8.0 (*)
│   ├── embassy-usb-driver v0.2.0 (*)
│   ├── embassy-usb-synopsys-otg v0.3.1
│   │   ├── critical-section v1.2.0
│   │   ├── defmt v1.0.1 (*)
│   │   ├── embassy-sync v0.7.2 (*)
│   │   └── embassy-usb-driver v0.2.0 (*)
│   ├── embedded-can v0.4.1
│   │   └── nb v1.1.0
│   ├── embedded-hal v0.2.7 (*)
│   ├── embedded-hal v1.0.0
│   ├── embedded-hal-async v1.0.0 (*)
│   ├── embedded-hal-nb v1.0.0
│   │   ├── embedded-hal v1.0.0
│   │   └── nb v1.1.0
│   ├── embedded-io v0.6.1 (*)
│   ├── embedded-io-async v0.6.1 (*)
│   ├── embedded-storage v0.3.1
│   ├── embedded-storage-async v0.4.1 (*)
│   ├── futures-util v0.3.31 (*)
│   ├── nb v1.1.0
│   ├── rand_core v0.6.4
│   ├── rand_core v0.9.3
│   ├── sdio-host v0.9.0
│   ├── static_assertions v1.1.0
│   ├── stm32-fmc v0.3.2
│   │   └── embedded-hal v0.2.7 (*)
│   ├── stm32-metapac v17.0.0
│   │   ├── cortex-m v0.7.7 (*)
│   │   ├── cortex-m-rt v0.7.5 (*)
│   │   └── defmt v0.3.100 (*)
│   ├── vcell v0.1.3
│   └── volatile-register v0.2.2 (*)
│   [build-dependencies]
│   ├── proc-macro2 v1.0.101 (*)
│   ├── quote v1.0.41 (*)
│   └── stm32-metapac v17.0.0
│       ├── cortex-m v0.7.7
│       │   ├── bare-metal v0.2.5
│       │   │   [build-dependencies]
│       │   │   └── rustc_version v0.2.3 (*)
│       │   ├── bitfield v0.13.2
│       │   ├── embedded-hal v0.2.7
│       │   │   ├── nb v0.1.3
│       │   │   │   └── nb v1.1.0
│       │   │   └── void v1.0.2
│       │   └── volatile-register v0.2.2
│       │       └── vcell v0.1.3
│       ├── cortex-m-rt v0.7.5
│       │   └── cortex-m-rt-macros v0.7.5 (proc-macro) (*)
│       └── defmt v0.3.100
│           └── defmt v1.0.1
│               ├── bitflags v1.3.2
│               └── defmt-macros v1.0.1 (proc-macro) (*)
├── embassy-sync v0.7.2 (*)
├── embassy-time v0.5.0
│   ├── cfg-if v1.0.4
│   ├── critical-section v1.2.0
│   ├── defmt v1.0.1 (*)
│   ├── document-features v0.2.11 (proc-macro) (*)
│   ├── embassy-time-driver v0.2.1 (*)
│   ├── embedded-hal v0.2.7 (*)
│   ├── embedded-hal v1.0.0
│   ├── embedded-hal-async v1.0.0 (*)
│   └── futures-core v0.3.31
├── embassy-usb v0.5.1 (*)
├── embedded-hal v1.0.0
├── embedded-hal-bus v0.3.0
│   ├── critical-section v1.2.0
│   └── embedded-hal v1.0.0
├── max31855-rs v0.1.0
│   ├── bit_field v0.10.3
│   └── embedded-hal v1.0.0
├── panic-probe v1.0.0
│   ├── cortex-m v0.7.7 (*)
│   └── defmt v1.0.1 (*)
├── postcard v1.1.3 (*)
├── postcard-rpc v0.11.15 (*)
├── serde v1.0.228 (*)
└── static_cell v2.1.1 (*)
```

</details>

**Comment by DCNick3** [comment]
You have both 0.7 and 0.8 in the dependency tree. This sounds a bit sus, since different major crate versions will get different sets of global variables. Might this be a situation where 0.7 creates the waker and puts its vtable and then 0.8 does the check against another vtable and complains?

Not sure why would `-Zcross-crate-inline-threshold=0` fix it though.

btw, providing a full minimal (or, I guess, any) reproducing example can help someone to debug this.

**Comment by Leandros** [comment]
> You have both 0.7 and 0.8 in the dependency tree

Yes. I noticed that as well. I agree that it's sus. That's why I supplied the `cargo tree` output. I'm forced to a previous version of `embassy-executor` due to `postcard-rpc` (https://github.com/jamesmunns/postcard-rpc/issues/134), but even if I were to use the latest version of `embassy-executor`, which would be v0.9, I would have `embassy-executor` v0.8 pulled in via `embassy-time-queue-utils` v0.2.0.

If that's the way the different versions of embassy-executor are interacting due to transitive dependencies that are out of my control, something is not working well here.

**Comment by Leandros** [comment]
Here is a minimal repro: https://github.com/Leandros/embassy-executor-min-repro

The alleged fix with `-Zcross-crate-inline-threshold=0` doesn't actually fix it either. It compiles, it flashes, and it runs, but it also doesn't make the timer work correctly. Any timer blocks forever.

The real fix is to use `embassy-executor` >= v0.8, which unfortunately locks me out of `postcard-rpc`.

**Comment by Dirbaio** [comment]
@Leandros it's expected you get this error if you mix embassy-executor versions. You must update postcard-rpc to the latest embassy-executor version, there's no other way out.

This issue is originally tracking a bug where this error would happen *even if you didn't mix embassy-executor versions*. This bug is no more, it was fixed in #2112. The `-Zcross-crate-inline-threshold=0` thing is a workaround for that bug, it's expected it doesn't do anything anymore.
